# Ejercicio 1> Agregar las variables de entorno necesarias para que la aplicacion "Flask" se conecte a MYSQL
# Ejercicio 2> Agregar php my admin a este docker-compose, y agregar nuevos varietales en la tabla wines del esquema drinks
# Ejercicio 3> Persistir el contenido de la base de datos mysql en disco
# Ejercicio 4> Hostear dos contenedores con la aplicación flask en puertos diferentes en el host (no hay que cambiar la aplicación)
# Ejercicio 5> Agregar al Dockerfile en ./app  la aplicación de linux "nano"

version: "2"

services:

  app:
    build: ./app
    depends_on:
      - db
    ports:
      - 8830:5000 #8830 - localhost del host, 5000 del container
    environment:
      DB_USER_NAME: root
      DB_PASSWORD: root
      NAME_HELLO: pepito

  app2:
    build: ./app
    depends_on:
      - db
    ports:
      - 8831:5000 #8831 - localhost del host, 5000 del container
    environment:
      DB_USER_NAME: root
      DB_PASSWORD: root
      NAME_HELLO: pepito2


  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - ./../db:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d/:ro

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - 8183:80



